version: '3'
services:
  app:
    build:
      context: .
      args:
        - CI_USER_TOKEN=${CI_USER_TOKEN}
        - DOCKER_DEV=1

    volumes:
      - .:/app

  environment:
    build:
      context: .
      args:
        - CI_USER_TOKEN=${CI_USER_TOKEN}
        - DOCKER_DEV=1

    volumes:
      - .:/app
